import random
welcome='''
-->>Welcome to the Number Guessing Game<<-- \n
The rules for playing the game are as follows:-\n
1. The user have to guess the random number generated by the system.
2. The user have 7 chances to guess the random number.
3. The random number is ranged from 0-100.\n'''

print(welcome.upper())
random_num=random.randint(0,101)
chances=7
guess=0
name=(input('Enter the name of the user-->>'))
while guess<chances:
    guess +=1
    
    user_guess=int(input('Enter the number you want to guess-->>'))
    if random_num==user_guess:
        print(f'Congratulation {name} !!!!! You guess the correct random number i.e,({random_num}).')
        break
    elif guess>=chances and user_guess!=random_num:
        print(f'Sorry {name}!!!! The random number is {random_num}.Better luck next time.Thank you for playing the game.')
    elif user_guess>random_num:
        print(f'{name},Your guess number is high.Guess the lower number than {user_guess} ')
    elif user_guess<random_num:
        print(f'{name},Your guess number is low.Guess the higher number than {user_guess}')
    

    